openapi: 3.0.3
info:
  title: SkyFollower Aircraft and Operator Microservice
  description: Aircraft Registration and Operator Information
  version: 1.0.0
servers:
  - url: 'http://{domain}:{port}'
    variables:
      domain:
        default: my.web.server.lan
        description: Domain or IP address of the microservice
      port:
        default: "8480"
        description: Port the microservice is listening

security:
  - ApiKeyAuth: []

tags:
  - name: Aircraft and Registration Data
  - name: Airline Operator Data

paths:

  /operator:
    get:
      deprecated: true
      tags:
       - Airline Operator Data
      description: Retrieve airline operator information by ICAO airline designator.
      summary: Retrieve airline operator information
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: airline_designator
          schema:
            $ref: '#/components/schemas/icao_airline_designator'
          description: ICAO airline designator, case insensitive
          example: DAL
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/operator_response'
              examples:
                British Airways:
                  $ref: '#/components/examples/operator_BAW'
                Delta Air Lines:
                  $ref: '#/components/examples/operator_DAL'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/operator_invalid_request'
        401:
          description: Unauthorized
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              
  /registration:
    get:
      tags:
       - Aircraft and Registration Data
      description: Retrieve an aicraft's registration and aircraft type information.  Either icao_hex or registration are required.
      summary: Retrieve an aicraft registration by ICAO Hex or Registration
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: icao_hex
          schema:
            type: string
            minLength: 6
            maxLength: 6
          description: ICAO hex of the aircraft to search, case insensitive
          example: A8AE7F
        - in: query
          name: registration
          schema:
            type: string
            minLength: 2
          description: Registration of the aircraft to search, case insensitive
          example: N659DL
        - in: query
          name: detailed
          schema:
            type: boolean
            default: false
          description: If specified, detailed information about the aircraft's registration is returned from a governmental source of authority
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/simple_registration'
                  - $ref: '#/components/schemas/detailed_registration'
              examples:
                Simple Registration, United States:
                  $ref: '#/components/examples/simple_registration_US'
                Simple Registration, Canada:
                  $ref: '#/components/examples/simple_registration_Canada'
                Detailed Registration, United States:
                  $ref: '#/components/examples/detailed_registration_US'
                Detailed Registration, Canada:
                  $ref: '#/components/examples/detailed_registration_Canada'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/registration_invalid_request'
        401:
          description: Unauthorized        
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
                
            



components:

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  schemas:

    error_message:
      type: object
      properties:
        error:
          type: string
          description: Message describing the error condition
          example: Unexpected Error

    simple_registration:
      type: object
      properties:
        icao_hex:
          $ref: '#/components/schemas/icao_hex'
        registration:
          $ref: '#/components/schemas/aircraft_registration'

    detailed_registration:
      type: object
      description: A country-specific registration record.  Only the fields below are guaranteed to be provided.  Other data in the object will be formatted per the governmental agency.
      properties:
        icao_hex:
          $ref: '#/components/schemas/icao_hex'
        registration:
          $ref: '#/components/schemas/aircraft_registration'
        aircraft:
          $ref: '#/components/schemas/detailed_aircraft'
        powerplant:
          $ref: '#/components/schemas/detailed_aircraft_power_plant'

    icao_hex:
      type: string
      description: The ICAO hexidecimal unique identifier for this aircraft
      minLength: 6
      maxLength: 6

    aircraft_registration:
      type: string
      description: The registration identifier ("tail number") painted on the side of the aircraft

    detailed_aircraft_power_plant:
      type: object
      description: Information about the aircraft's powerplant(s), country-specific

    detailed_aircraft:
      type: object
      description: Information about the aircraft, country-specific

    icao_airline_designator:
      type: string
      minLength: 3
      maxLength: 3
      description: ICAO airline designator

    operator_response:
      type: object
      properties:
        airline_designator:
          $ref: '#/components/schemas/icao_airline_designator'
        name:
          type: string
          description: Airline name
        callsign:
          type: string
          description: Radio callsign prepended to the flight number
        country:
          type: string
          description: Country of registration
  
  examples:

    registration_invalid_request:
      description: Neither the icao_hex nor registration was provided in the query, or BOTH were provided in the query
      value:
        error: Either 'icao_hex' or 'registration' parameter is required.

    operator_invalid_request:
      description: The airline_designator parameter was not provided
      value:
        error: Parameter 'airline_designator' is required.

    simple_registration_US:
      value:
        category: LandPlane
        icao_hex: A8AE7F
        military: false
        powerplant:
            type: Jet
            count: 2
        registration: N659DL
        type_designator: B752
        manufacturer_model: BOEING 757-200
        wake_turbulence_category: Medium

    simple_registration_Canada:
      value:
        category: LandPlane
        icao_hex: C01754
        military: false
        powerplant:
            type: Jet
            count: 2
        registration: C-FIVR
        type_designator: B77W
        manufacturer_model: BOEING 777-300ER
        wake_turbulence_category: Heavy

    detailed_registration_US:
      value:
        city: ATLANTA
        name: 
            - DELTA AIR LINES INC
        state: GA
        region: Southern
        status: Valid Registration
        street: 
          - 1775 M H JACKSON SERVICE RD
          - DEPT 595 AIRCRAFT REGISTRATIONS
        country: US
        aircraft:
            type: Fixed wing multi engine
            model: 757-232
            seats: 178
            weight: Exceeds 20,000lbs
            category: Land
            manufacturer: BOEING
            builder_certification: Type Certificated
        icao_hex: A8AE7F
        powerplant:
            count: 2
        last_action: "2020-07-16"
        postal_code: "303543743"
        registration: N659DL
        certification:
          - None
        serial_number: "24421"
        registrant_type: Corporation
        certificate_issue: "2017-08-30"
        manufactured_year: "1990"
        airworthiness_date: ""
        registration_expiration_date: "2023-08-31"
    
    detailed_registration_Canada:
      value:
        icao_hex: C01754
        registration: C-FIVR
        use: Commercial
        owners:
          - city: Dorval
            name: Air Canada
            type: Entity
            region: Quebec
            street:
              - Centre Air Canada, zip 1012
              - P.O. Box 9000, Station Airport
            country: CANADA
            province: Quebec
            postal_code: H4Y1C2
            mail_recipient: Yes
        status: Registered
        aircraft:
          model: 777-333ER
          weight: 351534.0
          category: Aeroplane
          manufacture_type: Manufactured
          eligibility_basis: CAR Standard 507.02, 507.03 - Type Certificate
          manufacturer_name: THE BOEING COMPANY
          country_manufactured: U.S.A.
          type_certificate_number:  A246
          manufacturer_name_common: Boeing
        issue_date: "2009-02-13"
        powerplant: 
          count: 2
          category: Turbo Fan
        import_date: "2009-01-20"
        modified_date: "2009-02-13"
        serial_number: "35241"
        effective_date: "2009-02-13"
        base_operations:
            base: Montréal Trudeau
            country: CANADA
            province: Quebec
        flight_authority: Certificate of Airworthiness
        manufactured_date: "2008-01-01"

    operator_BAW:
      value:
        airline_designator: BAW
        name: British Airways
        callsign: SPEEDBIRD
        country: United Kingdom

    operator_DAL:
      value:
        airline_designator: DAL
        name: Delta Air Lines
        callsign: DELTA
        country: United States

